include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: nvidia/cuda:latest


# Julia versions

julia:1.0:
  extends:
    - .julia:1.0
    - .test
  tags:
    - nvidia
    - sm_75

julia:1.1:
  extends:
    - .julia:1.1
    - .test
  tags:
    - nvidia
    - sm_75

julia:1.2:
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia
    - sm_75

julia:1.3:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia
    - sm_75

julia:nightly:
  extends:
    - .julia:nightly
    - .test
  tags:
    - nvidia
    - sm_75
  allow_failure: true


# CUDA versions

# NOTE: we support those CUDA versions for which the latest cuDNN is available
#       https://developer.nvidia.com/rdp/cudnn-archive

cuda:10.1:
  image: nvidia/cuda:10.1-devel
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia

cuda:10.0:
  image: nvidia/cuda:10.0-devel
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia

cuda:9.2:
  image: nvidia/cuda:9.2-devel
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia

cuda:9.0:
  image: nvidia/cuda:9.0-devel
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia


# reverse tests

# NOTE: reverse testing is tricky because of Manifests. we instantiate both, give priority
#       to this package's Manifest, and manually run tests outside of the test environment.
#       that means we have to manually install CuArrays' test dependencies though.

cuarrays:
  extends: .julia:1.2
  tags:
    - nvidia
    - sm_75
  image: juliagpu/cuda:10.1-cudnn7-cutensor-devel-ubuntu18.04
  script:
    - export CUARRAYS="$HOME/.julia/dev/CuArrays"
    - julia -e 'using Pkg;
                Pkg.develop("CuArrays");'
    - julia --project -e 'using Pkg;
                          Pkg.instantiate()'
    - julia --project=$CUARRAYS -e 'using Pkg;
                                    Pkg.instantiate();
                                    Pkg.add(["FFTW", "ForwardDiff"])'
    - JULIA_LOAD_PATH=".:$CUARRAYS::" julia $CUARRAYS/test/runtests.jl
  allow_failure: true


# other tasks

coverage:
  extends:
    - .julia:1.2
    - .coverage

documentation:
  extends:
    - .julia:1.2
    - .documentation
  tags:
    - nvidia

pages:
  stage: deploy
  script:
    - mv docs/build public
  artifacts:
    paths:
    - public
  only:
    - master
