variables:
  CI_IMAGE_TAG: 'cuda'
  JULIA_NUM_THREADS: '4'

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v5/test.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v5/coverage.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v5/documentation.yml'


# basic tests

test:v1.0:
  extends: .test:v1.0

test:v1.1:
  extends: .test:v1.1

test:v1.2:
  extends: .test:v1.2

test:v1.3:
  extends: .test:v1.3
  allow_failure: true

test:dev:
  extends: .test:dev
  allow_failure: true


# special tests

test:v1.2-split:
  extends: .test:v1.2
  variables:
    CUARRAYS_MEMORY_POOL: 'split'


# reverse tests

# NOTE: not using the Manifest (develop instead of instantiate) due to Pkg.jl#1423

flux:
  extends: .test:v1.2
  script:
    - julia -e 'using Pkg;
                Pkg.develop(PackageSpec(path=pwd()));
                Pkg.build();'
    - julia -e 'using Pkg;
                Pkg.add("Flux");
                Pkg.test("Flux");'
  allow_failure: true


# deployment

pages:
  stage: deploy
  script:
    - mv docs/build public
  artifacts:
    paths:
    - public
  only:
    - master
