variables:
  CI_IMAGE_TAG: 'cuda'
  CI_DEV_PKGS: 'CUDAdrv LLVM'

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/common.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_v1.0.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_v1.1.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_v1.2.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_dev.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/coverage_v1.1.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/documentation_v1.1.yml'

test:dev:
  allow_failure: true

coverage:
  allow_failure: true
  only:
    - master

pages:
  stage: deploy
  script:
    - mv docs/build public
  artifacts:
    paths:
    - public
  only:
    - master

cuarrays:
  stage: test
  image: "juliagpu/julia:v1.1-cuda"
  script:
    - mkdir $JULIA_DEPOT_PATH # Pkg.jl#325
    - julia -e 'using Pkg;
                Pkg.develop([PackageSpec(path=pwd());
                             [PackageSpec(name=pkg)
                              for pkg in split(get(ENV,"CI_DEV_PKGS",""))]]);
                Pkg.build("CUDAnative")'
    - julia -e 'using Pkg;
                Pkg.add("CuArrays");
                Pkg.test("CuArrays")'
  allow_failure: true
