variables:
  CI_IMAGE_TAG: 'cuda'

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v2/common.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v2/test_v1.0.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v2/test_v1.1.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v2/test_dev.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v2/coverage_v1.1.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v2/documentation_v1.1.yml'

test:v1.0:
  only:
    - master
    - staging
    - trying

test:v1.1:
  only:
    - master
    - staging
    - trying

test:dev:
  allow_failure: true
  only:
    - master
    - staging
    - trying

coverage:
  allow_failure: true
  only:
    - master
    - staging
    - trying

documentation:
  only:
    - master
    - staging
    - trying

tutorial:
  stage: post
  image: "juliagpu/julia:v1.1-${CI_IMAGE_TAG}"
  variables:
    JULIA_NUM_THREADS: "4"
  dependencies:
    - test:v1.1
  script:
    - julia --project=tutorials/ -e 'using Pkg;
                                     Pkg.develop(PackageSpec(path=pwd()));
                                     Pkg.instantiate()'
    - julia --project=tutorials/ tutorials/make.jl
  artifacts:
    paths:
    - tutorials/build
  only:
    - master
    - staging
    - trying

pages:
  stage: deploy
  script:
    - mv docs/build public
    - mv tutorials/build public/tutorials
  artifacts:
    paths:
    - public
  only:
    - master

flux:
  stage: test
  image: "juliagpu/julia:v1.1-cuda"
  script:
    - mkdir $JULIA_DEPOT_PATH # Pkg.jl#325
    - julia -e 'using Pkg;
                Pkg.develop(PackageSpec(path=pwd()));
                Pkg.build();
                Pkg.add(PackageSpec(name="Flux", rev="master"));
                Pkg.test("Flux");'
  allow_failure: true
  only:
    - master
    - staging
    - trying
