include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: nvidia/cuda:latest


# basic tests

test:1.0:
  extends:
    - .julia:1.0
    - .test

test:1.1:
  extends:
    - .julia:1.1
    - .test

test:1.2:
  extends:
    - .julia:1.2
    - .test

test:1.3:
  extends:
    - .julia:1.3
    - .test

test:nightly:
  extends:
    - .julia:nightly
    - .test
  allow_failure: true


# reverse tests

# NOTE: not using the Manifest (develop instead of instantiate) due to Pkg.jl#1423

cuarrays:
  extends: .julia:1.2
  image: juliagpu/cuda:10.1-cudnn7-cutensor-devel-ubuntu18.04
  script:
    - julia -e 'using Pkg;
                Pkg.develop(PackageSpec(path=pwd()));
                Pkg.build();'
    - julia -e 'using Pkg;
                Pkg.add(PackageSpec(name="CuArrays", rev="master"));
                Pkg.test("CuArrays");'
  allow_failure: true


# other tasks

coverage:
  extends:
    - .julia:1.2
    - .coverage

documentation:
  extends:
    - .julia:1.2
    - .documentation

pages:
  stage: deploy
  script:
    - mv docs/build public
  artifacts:
    paths:
    - public
  only:
    - master
