include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: ubuntu:bionic

variables:
  JULIA_DEBUG: 'CUDAnative'
  NVIDIA_VISIBLE_DEVICES: 'all'
  NVIDIA_DRIVER_CAPABILITIES: 'all'


# Julia versions

# the "primary" target, where we require a new GPU to make sure all tests are run
julia:1.3:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia
    - sm_75
  variables:
    CI_THOROUGH: 'true'

# julia:nightly:
#   extends:
#     - .julia:nightly
#     - .test
#   tags:
#     - nvidia
#     - sm_75
#   variables:
#     CI_THOROUGH: 'true'
#   allow_failure: true

julia:1.4-debug:
  extends:
    - .julia:source
    - .test
  tags:
    - nvidia
  variables:
    CI_CLONE_ARGS: '-b release-1.4'
    CI_BUILD_ARGS: 'BINARYBUILDER_LLVM_ASSERTS=1 debug'
  allow_failure: true


# CUDA versions

# NOTE: we support those CUDA versions for which the latest cuDNN is available
#       https://developer.nvidia.com/rdp/cudnn-archive

cuda:10.1:
  extends:
    - .julia:1.3
    - .test
  variables:
    JULIA_CUDA_VERSION: '10.1'
  tags:
    - nvidia

cuda:10.0:
  extends:
    - .julia:1.3
    - .test
  variables:
    JULIA_CUDA_VERSION: '10.0'
  tags:
    - nvidia

cuda:9.2:
  extends:
    - .julia:1.3
    - .test
  variables:
    JULIA_CUDA_VERSION: '9.2'
  tags:
    - nvidia

cuda:9.0:
  extends:
    - .julia:1.3
    - .test
  variables:
    JULIA_CUDA_VERSION: '9.0'
  tags:
    - nvidia

cuda:local:
  extends:
    - .julia:1.3
    - .test
  image: nvidia/cuda:10.1-devel-ubuntu18.04
  variables:
    JULIA_CUDA_USE_BINARYBUILDER: 'false'
  tags:
    - nvidia

cuda:none:
  extends:
    - .julia:1.3
    - .test
  variables:
    JULIA_CUDA_USE_BINARYBUILDER: 'false'
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.instantiate();
                          Pkg.build();
                          Pkg.API.precompile()'
    - julia --project -e 'using CUDAnative;
                          CUDAnative.load_runtime(v"7.0")'


# hardware platforms

platform:arm64:
  image: nvcr.io/nvidia/l4t-base:r32.2.1
  variables:
    JULIA_CUDA_USE_BINARYBUILDER: 'false'
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia-arm64


# special tests

debug:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia
  script:
    - julia --project -g2 -e 'using Pkg;
                              Pkg.instantiate();
                              Pkg.build();
                              Pkg.test(; coverage=true);'


# reverse tests

# NOTE: reverse testing is tricky because of Manifests. we instantiate both, give priority
#       to this package's Manifest, and manually run tests outside of the test environment.
#       that means we have to manually install CuArrays' test dependencies though.

cuarrays:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia
  image: nvidia/cuda:10.1-devel
  variables:
    JULIA_CUDA_USE_BINARYBUILDER: 'false'
  script:
    - export CUARRAYS=".julia/dev/CuArrays"
    - julia -e 'using Pkg;
                Pkg.develop("CuArrays");'
    - julia --project -e 'using Pkg;
                          Pkg.instantiate()'
    - julia --project=$CUARRAYS -e 'using Pkg;
                                    Pkg.instantiate();
                                    Pkg.add(["FFTW", "ForwardDiff", "FillArrays"])'
    - JULIA_LOAD_PATH=".:$CUARRAYS::" julia $CUARRAYS/test/runtests.jl
  allow_failure: true


# other tasks

coverage:
  extends:
    - .julia:1.3
    - .coverage

documentation:
  extends:
    - .julia:1.3
    - .documentation
  tags:
    - nvidia

pages:
  stage: deploy
  script:
    - mv docs/build public
  artifacts:
    paths:
    - public
  only:
    - master
