variables:
  CI_IMAGE_TAG: 'cuda'

stages:
  - test
  - postprocess

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v1/common.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v1/test_v1.0.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v1/test_dev.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v1/coverage_dev.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/dev/documentation_v1.0.yml'

test:v1.0:
  only:
    - master
    - staging
    - trying

test:dev:
  allow_failure: true
  only:
    - master
    - staging
    - trying

documentation:
  only:
    - master
    - staging
    - trying

coverage:
  only:
    - master
    - staging
    - trying

flux:
  stage: test
  image: "juliagpu/julia:v1.0-cuda"
  script:
    - mkdir $JULIA_DEPOT_PATH # Pkg.jl#325
    - julia -e 'using Pkg;
                Pkg.develop(PackageSpec(path=pwd()));
                Pkg.build();
                Pkg.add(PackageSpec(name="Flux", rev="master"));
                Pkg.test("Flux");'
  allow_failure: true
  only:
    - master
    - staging
    - trying
