language: julia

sudo: required

notifications:
  email: false

julia: 1.3
osx_image: xcode11.3
dist: xenial

env:
  global:
    - JULIA_DEBUG=CUDAapi

matrix:
  include:
    # linux builds
    - env: CUDA=9.0
      os: linux
    - env: CUDA=9.2
      os: linux
    - env: CUDA=10.0
      os: linux
    - env: CUDA=10.1
      os: linux
    - env: CUDA=10.2
      os: linux
    # osx builds
    - env: CUDA=9.0
      os: osx
    - env: CUDA=9.2
      os: osx
    - env: CUDA=10.0
      os: osx
    - env: CUDA=10.1
      os: osx
    - env: CUDA=10.2
      os: osx
    # julia nightly
    - env: CUDA=10.0
      os: linux
      julia: nightly

addons:
  homebrew:
    packages:
    - bash
    - p7zip
    - gnu-tar

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]];   then                   ./.travis.linux;   fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]];     then /usr/local/bin/bash .travis.osx;     fi
