language: julia

sudo: required

notifications:
  email: false

julia: 0.7

env:
  global:
    - JULIA_DEBUG=CUDAapi

matrix:
  include:
    # linux builds
    - env: CUDA=8.0
      os: linux
      dist: xenial
    - env: CUDA=9.0
      os: linux
      dist: xenial
    - env: CUDA=9.1
      os: linux
      dist: xenial
    - env: CUDA=9.2
      os: linux
      dist: xenial
    - env: CUDA=10.0
      os: linux
      dist: xenial
    # osx builds
    - env: CUDA=7.5
      os: osx
      osx_image: xcode7.3
    - env: CUDA=8.0
      os: osx
      osx_image: xcode7.3
    - env: CUDA=9.0
      os: osx
      osx_image: xcode7.3
    - env: CUDA=9.1
      os: osx
      osx_image: xcode7.3
    - env: CUDA=9.2
      os: osx
      osx_image: xcode7.3
    - env: CUDA=10.0
      os: osx
      osx_image: xcode7.3
    # julia nightly
    - env: CUDA=10.0
      os: linux
      dist: xenial
      julia: nightly

branches:
  only:
    - staging
    - trying

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then ./.travis.linux; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]];   then ./.travis.osx;   fi
