# CUDA

[[CUDA100]]
arch = "x86_64"
git-tree-sha1 = "6ec6cce0e6bd5457462da63c679c3a2cd4c53d0c"
lazy = true
os = "macos"

    [[CUDA100.download]]
    sha256 = "353011cc145ff9037bee4bb55b13f2a0408b0e1489365fdbf26ca0d60e876888"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.0.130+1/CUDA.v10.0.130.x86_64-apple-darwin14.tar.gz"

[[CUDA100]]
arch = "x86_64"
git-tree-sha1 = "d18cf3a0b21c79e3ef653b78e879da52de81b39b"
lazy = true
os = "windows"

    [[CUDA100.download]]
    sha256 = "bd8fe993b33890518e897ea5706f224adf3430afeb943de20e4021b7af93dd26"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.0.130+1/CUDA.v10.0.130.x86_64-w64-mingw32.tar.gz"

[[CUDA100]]
arch = "x86_64"
git-tree-sha1 = "07974e46024630c7d8a3addf5223aaa72c20c47e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA100.download]]
    sha256 = "e1c5d320bf6e00bef6a7d3a2692a7e171817bf1ff7e398d07741b03ca9bbd0e6"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.0.130+1/CUDA.v10.0.130.x86_64-linux-gnu.tar.gz"

[[CUDA101]]
arch = "x86_64"
git-tree-sha1 = "d479faf5c3d181e74970da3111df37669160e8fc"
lazy = true
os = "windows"

    [[CUDA101.download]]
    sha256 = "e9b8d71f45fa2c0137796037fdb9041a08276e1e40f93a56e5767bd306ecd48f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.1.243+3/CUDA.v10.1.243.x86_64-w64-mingw32.tar.gz"

[[CUDA101]]
arch = "x86_64"
git-tree-sha1 = "b502baf54095dff4a69fd6aba8667124583f6929"
lazy = true
os = "macos"

    [[CUDA101.download]]
    sha256 = "fe5996c75daffc57ad6ed7400da12ef18742f50ab8ea8a8ab070d1f57c9730fa"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.1.243+3/CUDA.v10.1.243.x86_64-apple-darwin14.tar.gz"

[[CUDA101]]
arch = "x86_64"
git-tree-sha1 = "1548f2a8ab23b1759621586b63ed06fa8f36340d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA101.download]]
    sha256 = "a80cfa12f215e5fe8543cd35bde8b298dc71f6a63d0f92058d361152a3cbb536"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.1.243+3/CUDA.v10.1.243.x86_64-linux-gnu.tar.gz"

[[CUDA102]]
arch = "x86_64"
git-tree-sha1 = "541f02f35c01bada7332413510ee4b1c6f4a4d5b"
lazy = true
os = "windows"

    [[CUDA102.download]]
    sha256 = "757a26c3535b397255673046bd6675d89967075a56dbedcc6316d691affc7260"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.2.89+3/CUDA.v10.2.89.x86_64-w64-mingw32.tar.gz"

[[CUDA102]]
arch = "x86_64"
git-tree-sha1 = "ad4ce98c5e8ed603ad80bf41817e20485129552c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA102.download]]
    sha256 = "00b0b60564e8868d0973fdde99f1e91ca8f8d54fefd569c2082823715153c0dc"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.2.89+3/CUDA.v10.2.89.x86_64-linux-gnu.tar.gz"

[[CUDA110]]
arch = "x86_64"
git-tree-sha1 = "7670a86e87b992ec4edb1c9eaeca8e57e15eeb4c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA110.download]]
    sha256 = "d6a66304e09a46ee8c307b314145d8073b4c08b9ed1da787ac4edcf93c067705"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.0.3+0/CUDA.v11.0.3.x86_64-linux-gnu.tar.gz"

[[CUDA110]]
arch = "x86_64"
git-tree-sha1 = "796965836d2cdbc7c12c2d896800285d3c266cef"
lazy = true
os = "windows"

    [[CUDA110.download]]
    sha256 = "e3dc82507ac1f16d740970df87a1e75898a6b62479057a419ad6ccfb02b60ba0"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.0.3+0/CUDA.v11.0.3.x86_64-w64-mingw32.tar.gz"

[[CUDA111]]
arch = "x86_64"
git-tree-sha1 = "23ec8861ac0539b1549ce37ba12a88182c28adb4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA111.download]]
    sha256 = "b8962decd879fae212e0362f2ea5ec5161a9f41f2769e3ce59018f004ca52914"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.1.0+0/CUDA.v11.1.0.x86_64-linux-gnu.tar.gz"

[[CUDA111]]
arch = "x86_64"
git-tree-sha1 = "75593c2ea86a066db0435c3e73dd82cbed892e6f"
lazy = true
os = "windows"

    [[CUDA111.download]]
    sha256 = "89f5a81c3a0bb38148ba70e2e14ca52235ce71d3ae113f201df9dbba1eec80b3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.1.0+0/CUDA.v11.1.0.x86_64-w64-mingw32.tar.gz"


# CUDNN

[[CUDNN_CUDA101]]
arch = "x86_64"
git-tree-sha1 = "65e3425ecb85689a1b04750fb6484cecfafab25b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA101.download]]
    sha256 = "340271e2131bafb23ddbf04c26414d8cc7a0ec69731088c69e345c71dc77557a"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA101_jll.jl/releases/download/CUDNN_CUDA101-v8.0.2+0/CUDNN_CUDA101.v8.0.2.x86_64-linux-gnu.tar.gz"

[[CUDNN_CUDA101]]
arch = "powerpc64le"
git-tree-sha1 = "baaf4a1efdeade6368c51aff26b394eec48cfab8"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA101.download]]
    sha256 = "758c6837fe61c50ff23cf19b6ea6852c45fb398d7c327e3df08442879be79d46"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA101_jll.jl/releases/download/CUDNN_CUDA101-v8.0.2+0/CUDNN_CUDA101.v8.0.2.powerpc64le-linux-gnu.tar.gz"

[[CUDNN_CUDA101]]
arch = "x86_64"
git-tree-sha1 = "f52953d0bfb0d4a6d04643cdb71566850adaf167"
lazy = true
os = "windows"

    [[CUDNN_CUDA101.download]]
    sha256 = "30c2a1eafef25fac6188891d23c8ead760d73c8029c1f830ae0b6b5ef4341013"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA101_jll.jl/releases/download/CUDNN_CUDA101-v8.0.2+0/CUDNN_CUDA101.v8.0.2.x86_64-w64-mingw32.tar.gz"

[[CUDNN_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "b2cd5f61ce1f9cf00cb94000f20d99b125140255"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA102.download]]
    sha256 = "93c0af9091b17666056bdf333ea12025827944b678b5db95a2473d5a6f909269"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA102_jll.jl/releases/download/CUDNN_CUDA102-v8.0.2+0/CUDNN_CUDA102.v8.0.2.x86_64-linux-gnu.tar.gz"

[[CUDNN_CUDA102]]
arch = "powerpc64le"
git-tree-sha1 = "6e3021ae675e6d016e203be01d25fad9809d00e4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA102.download]]
    sha256 = "2defb113c23828317295bea84f63434d7bf7836105bf6dfe0b039d54bed851c9"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA102_jll.jl/releases/download/CUDNN_CUDA102-v8.0.2+0/CUDNN_CUDA102.v8.0.2.powerpc64le-linux-gnu.tar.gz"

[[CUDNN_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "4d76a9ff68e83dbac1a519fa9ce631e9ec8b291e"
lazy = true
os = "windows"

    [[CUDNN_CUDA102.download]]
    sha256 = "5958fb195fc272e6c31535a627639e41d6a5c0b3046f39947436001509361aa5"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA102_jll.jl/releases/download/CUDNN_CUDA102-v8.0.2+0/CUDNN_CUDA102.v8.0.2.x86_64-w64-mingw32.tar.gz"

[[CUDNN_CUDA110]]
arch = "x86_64"
git-tree-sha1 = "88dc9adaa9ab5841c6d61f4cb3105ebacd95b95d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA110.download]]
    sha256 = "6d89beb510c01a176d467fb2e3ac431341b7930ae1091f6a0d42556b39eaa8c8"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA110_jll.jl/releases/download/CUDNN_CUDA110-v8.0.2+0/CUDNN_CUDA110.v8.0.2.x86_64-linux-gnu.tar.gz"

[[CUDNN_CUDA110]]
arch = "powerpc64le"
git-tree-sha1 = "e8b397697524c60694e48c80749bf6b54f237e64"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA110.download]]
    sha256 = "dc96d3e988e12562cef500f67cca0bd0fcc48684b4da6bfd1460ae0c81edf46d"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA110_jll.jl/releases/download/CUDNN_CUDA110-v8.0.2+0/CUDNN_CUDA110.v8.0.2.powerpc64le-linux-gnu.tar.gz"

[[CUDNN_CUDA110]]
arch = "x86_64"
git-tree-sha1 = "c68026379752255051652cc354aab4c74bd21dec"
lazy = true
os = "windows"

    [[CUDNN_CUDA110.download]]
    sha256 = "41eeb517b0addb41cf204a4c0f7082a9af031fe734b5067675bde6b40733b2d1"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA110_jll.jl/releases/download/CUDNN_CUDA110-v8.0.2+0/CUDNN_CUDA110.v8.0.2.x86_64-w64-mingw32.tar.gz"


# CUTENSOR

[[CUTENSOR_CUDA101]]
arch = "x86_64"
git-tree-sha1 = "16dcf8a61c4b9b3304a48e9f474bdc51f722bcfb"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA101.download]]
    sha256 = "df9e79b72bd0e862443b485694a66f09811181e822b2ca5526a373ed7c18b632"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA101_jll.jl/releases/download/CUTENSOR_CUDA101-v1.2.0+0/CUTENSOR_CUDA101.v1.2.0.x86_64-linux-gnu.tar.gz"

[[CUTENSOR_CUDA101]]
arch = "powerpc64le"
git-tree-sha1 = "3cca8368bbe4965846a77d4be89914bd6f71e0d7"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA101.download]]
    sha256 = "0f66003f90e2554622f7f1bcd50202b4cb6428de6cf8315cb65c29efd5f66c55"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA101_jll.jl/releases/download/CUTENSOR_CUDA101-v1.2.0+0/CUTENSOR_CUDA101.v1.2.0.powerpc64le-linux-gnu.tar.gz"

[[CUTENSOR_CUDA101]]
arch = "x86_64"
git-tree-sha1 = "48d1784fa4999a51262fd71d80963ea93018f4b7"
lazy = true
os = "windows"

    [[CUTENSOR_CUDA101.download]]
    sha256 = "5efce496c330cd9f6df38b93e605127977f0221ca023a4c864bb9e2bc48dd595"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA101_jll.jl/releases/download/CUTENSOR_CUDA101-v1.2.0+0/CUTENSOR_CUDA101.v1.2.0.x86_64-w64-mingw32.tar.gz"

[[CUTENSOR_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "22ae18c36ae1627644e3f7bf7bcf5ffc38f1139e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA102.download]]
    sha256 = "086c7717d18632ba3027d37d3d0e2b27995996407474f2f0845b51e18ca34bde"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA102_jll.jl/releases/download/CUTENSOR_CUDA102-v1.2.0+0/CUTENSOR_CUDA102.v1.2.0.x86_64-linux-gnu.tar.gz"

[[CUTENSOR_CUDA102]]
arch = "powerpc64le"
git-tree-sha1 = "c7daacb1595742713af9785268bc3c938f259d11"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA102.download]]
    sha256 = "1148373079d63cb4517259d65353a2f9e7f0d109bb05f219019caf80b75b1122"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA102_jll.jl/releases/download/CUTENSOR_CUDA102-v1.2.0+0/CUTENSOR_CUDA102.v1.2.0.powerpc64le-linux-gnu.tar.gz"

[[CUTENSOR_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "d6605f4aac98265f0bc1e17d7b6442ffbdee6e9a"
lazy = true
os = "windows"

    [[CUTENSOR_CUDA102.download]]
    sha256 = "23830ae8da7eaaaef63b572ff19a47f3a86ca7124b8ce2c85bd76286cbf58014"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA102_jll.jl/releases/download/CUTENSOR_CUDA102-v1.2.0+0/CUTENSOR_CUDA102.v1.2.0.x86_64-w64-mingw32.tar.gz"

[[CUTENSOR_CUDA110]]
arch = "x86_64"
git-tree-sha1 = "12a771b8cabb526e7ca8a897e19b144d1f517079"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA110.download]]
    sha256 = "33d301405a4e6e10d3c44304c419b004f0cfc89a1e81cc483b4b2067b6f1b0bb"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.0+0/CUTENSOR_CUDA110.v1.2.0.x86_64-linux-gnu.tar.gz"

[[CUTENSOR_CUDA110]]
arch = "powerpc64le"
git-tree-sha1 = "8b5c5ccf3a2233b8a1730ee5160294caef91b1c0"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA110.download]]
    sha256 = "5f0ce5d2d0f94c7d096bf6317d5425e66381ec9aa41942904570f982a03a4269"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.0+0/CUTENSOR_CUDA110.v1.2.0.powerpc64le-linux-gnu.tar.gz"

[[CUTENSOR_CUDA110]]
arch = "x86_64"
git-tree-sha1 = "804435c7dbe9d002d6caa0a8b3596d11a6faa778"
lazy = true
os = "windows"

    [[CUTENSOR_CUDA110.download]]
    sha256 = "a2ff02ca1003f6e96e63335e6296637173d02cf9d44892225815679dc9c13ee7"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.0+0/CUTENSOR_CUDA110.v1.2.0.x86_64-w64-mingw32.tar.gz"
