name = "CUDAapi"
uuid = "3895d2a7-ec45-59b8-82bb-cfc6a382f9b3"
version = "3.1.0"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
