name = "CUDAnative"
uuid = "be33ccc6-a3ff-5ff2-a52e-74243cff1e17"
version = "2.8.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
CUDAapi = "3895d2a7-ec45-59b8-82bb-cfc6a382f9b3"
CUDAdrv = "c5f51814-7f29-56b8-a69c-e4d8f6be1fde"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
Adapt = "0.4, 1.0"
CEnum = "0.2"
CUDAapi = "2.0"
CUDAdrv = "5.0"
DataStructures = "0.15, 0.16, 0.17"
LLVM = "1.2"
TimerOutputs = "0.5"
julia = "1.3"

[extras]
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CuArrays"]
