include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: nvidia/cuda:10.1-devel

variables:
  JULIA_DEBUG: 'CUDAapi'


# Julia versions

julia:1.0:
  extends:
    - .julia:1.0
    - .test
  tags:
    - nvidia

julia:1.1:
  extends:
    - .julia:1.1
    - .test
  tags:
    - nvidia

julia:1.2:
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia

julia:1.3:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia

julia:nightly:
  extends:
    - .julia:nightly
    - .test
  tags:
    - nvidia
  allow_failure: true


# CUDA versions

# NOTE: we support those CUDA versions for which the latest cuDNN is available
#       https://developer.nvidia.com/rdp/cudnn-archive

cuda:10.1:
  image: nvidia/cuda:10.1-devel
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia

cuda:10.0:
  image: nvidia/cuda:10.0-devel
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia

cuda:9.2:
  image: nvidia/cuda:9.2-devel
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia

cuda:9.0:
  image: nvidia/cuda:9.0-devel
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia


# other tasks

coverage:
  extends:
    - .julia:1.3
    - .coverage
