include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: ubuntu:bionic

variables:
  JULIA_NUM_THREADS: '4'
  JULIA_DEBUG: 'CuArrays'
  CI_APT_INSTALL: 'libgomp1'
  NVIDIA_VISIBLE_DEVICES: 'all'
  NVIDIA_DRIVER_CAPABILITIES: 'compute,utility'


# Julia versions

# the "primary" target, where we require thorough tests
# (this requires a recent GPU)
julia:1.3:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia
    - sm_70
  variables:
    CI_THOROUGH: 'true'

julia:1.4:
  extends:
    - .julia:1.4
    - .test
  tags:
    - nvidia

# julia:nightly:
#   extends:
#     - .julia:nightly
#     - .test
#   tags:
#     - nvidia
#   allow_failure: true


# CUDA versions

# NOTE: we support those CUDA versions for which the latest cuDNN is available
#       https://developer.nvidia.com/rdp/cudnn-archive

cuda:10.1:
  extends:
    - .julia:1.3
    - .test
  variables:
    JULIA_CUDA_VERSION: '10.1'
  tags:
    - nvidia

cuda:10.0:
  extends:
    - .julia:1.3
    - .test
  variables:
    JULIA_CUDA_VERSION: '10.0'
  tags:
    - nvidia

cuda:9.2:
  extends:
    - .julia:1.3
    - .test
  variables:
    JULIA_CUDA_VERSION: '9.2'
  tags:
    - nvidia

# NOTE: CUDA 9.0 is broken

cuda:local:
  extends:
    - .julia:1.3
    - .test
  image: nvidia/cuda:10.1-devel-ubuntu18.04
  variables:
    JULIA_CUDA_USE_BINARYBUILDER: 'false'
  tags:
    - nvidia

cuda:none:
  extends:
    - .julia:1.3
    - .test
  variables:
    JULIA_CUDA_USE_BINARYBUILDER: 'false'
  script:
    - julia --project -e 'using Pkg;
                          Pkg.instantiate();
                          Pkg.build()'
    - julia --project -e 'using CuArrays;
                          @assert !CuArrays.functional(true)'


# hardware platforms

platform:arm64:
  image: nvcr.io/nvidia/l4t-base:r32.3.1
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia-arm64
  allow_failure: true


# special tests

pool:none:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia
  variables:
    JULIA_CUDA_MEMORY_POOL: 'none'

pool:simple:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia
  variables:
    JULIA_CUDA_MEMORY_POOL: 'simple'

pool:split:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia
  variables:
    JULIA_CUDA_MEMORY_POOL: 'split'
  allow_failure: true

debug:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia
  script:
    - julia --project -g2 -e 'using Pkg;
                              Pkg.instantiate();
                              Pkg.build();
                              Pkg.test(; coverage=true);'


# reverse tests

# NOTE: reverse testing is tricky because of Manifests. we instantiate both, give priority
#       to this package's Manifest, and manually run tests outside of the test environment.
#       that means we have to manually install Flux' test dependencies though.

flux:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia
  script:
    - export FLUX=".julia/dev/Flux"
    - julia -e 'using Pkg;
                Pkg.develop("Flux");'
    - julia --project -e 'using Pkg;
                          Pkg.instantiate()'
    - julia --project=$FLUX -e 'using Pkg;
                                Pkg.instantiate();
                                Pkg.add(["Documenter", "IterTools"])'
    - JULIA_LOAD_PATH=".:$FLUX::" julia $FLUX/test/runtests.jl
  allow_failure: true


# other tasks

coverage:
  extends:
    - .julia:1.3
    - .coverage

documentation:
  extends:
    - .julia:1.3
    - .documentation
  tags:
    - nvidia

pages:
  stage: deploy
  script:
    - mv docs/build public
  artifacts:
    paths:
    - public
  only:
    - master
