[general]
library_name = "libcublas"
output_file_path = "../../lib/cublas/libcublas.jl"
prologue_file_path = "./libcublas_prologue.jl"
epilogue_file_path = "./libcublas_epilogue.jl"

output_ignorelist = [
    # these change often
    "CUBLAS_VERSION",
    "CUBLAS_VER_.*",
]


[codegen]
use_ccall_macro = true
always_NUL_terminated_string = true


[api]
checked_rettypes = [ "cublasStatus_t" ]

[api.cublasGetVersion_v2]
needs_context = false

[api.cublasGetProperty]
needs_context = false

[api.cublasGetCudartVersion]
needs_context = false

[api.cublasSetLoggerCallback]
needs_context = false

[api.cublasGetLoggerCallback]
needs_context = false

[api.cublasCreate_v2.argtypes]
1 = "Ref{cublasHandle_t}"

[api.cublasGetVersion_v2.argtypes]
2 = "Ref{Cint}"

[api.cublasGetProperty.argtypes]
2 = "Ref{Cint}"

[api.cublasGetStream_v2.argtypes]
2 = "Ref{CUstream}"

[api.cublasGetPointerMode_v2.argtypes]
2 = "Ref{cublasPointerMode_t}"

[api.cublasGetAtomicsMode.argtypes]
2 = "Ref{cublasAtomicsMode_t}"

[api.cublasGetMathMode.argtypes]
2 = "Ref{UInt32}"

[api.cublasGetLoggerCallback.argtypes]
1 = "Ref{cublasLogCallback}"

[api.cublasSetVector.argtypes]
5 = "CuPtr{Cvoid}"

[api.cublasGetVector.argtypes]
3 = "CuPtr{Cvoid}"

[api.cublasSetMatrix.argtypes]
6 = "CuPtr{Cvoid}"

[api.cublasGetMatrix.argtypes]
4 = "CuPtr{Cvoid}"

[api.cublasSetVectorAsync.argtypes]
5 = "CuPtr{Cvoid}"

[api.cublasGetVectorAsync.argtypes]
3 = "CuPtr{Cvoid}"

[api.cublasSetMatrixAsync.argtypes]
6 = "CuPtr{Cvoid}"

[api.cublasGetMatrixAsync.argtypes]
4 = "CuPtr{Cvoid}"

[api.cublasNrm2Ex.argtypes]
3 = "CuPtr{Cvoid}"
6 = "PtrOrCuPtr{Cvoid}"

[api."cublasğ•nrm2_v2".argtypes]
3 = "CuPtr{T}"
5 = "RefOrCuRef{T}"

[api.cublasScnrm2_v2.argtypes]
3 = "CuPtr{cuComplex}"
5 = "RefOrCuRef{Cfloat}"

[api.cublasDznrm2_v2.argtypes]
3 = "CuPtr{cuDoubleComplex}"
5 = "RefOrCuRef{Cdouble}"

[api.cublasDotEx.argtypes]
3 = "CuPtr{Cvoid}"
6 = "CuPtr{Cvoid}"
9 = "PtrOrCuPtr{Cvoid}"

[api.cublasDotcEx.argtypes]
3 = "CuPtr{Cvoid}"
6 = "CuPtr{Cvoid}"
9 = "PtrOrCuPtr{Cvoid}"

[api."cublasğ•dot_v2".argtypes]
3 = "CuPtr{T}"
5 = "CuPtr{T}"
7 = "RefOrCuRef{T}"

[api."cublasğ•dotu_v2".argtypes]
3 = "CuPtr{T}"
5 = "CuPtr{T}"
7 = "RefOrCuRef{T}"

[api."cublasğ•dotc_v2".argtypes]
3 = "CuPtr{T}"
5 = "CuPtr{T}"
7 = "RefOrCuRef{T}"

[api.cublasScalEx.argtypes]
3 = "PtrOrCuPtr{Cvoid}"
5 = "CuPtr{Cvoid}"

[api."cublasğ•scal_v2".argtypes]
3 = "RefOrCuRef{T}"
4 = "CuPtr{T}"

[api.cublasCsscal_v2.argtypes]
3 = "RefOrCuRef{Cfloat}"
4 = "CuPtr{cuComplex}"

[api.cublasZdscal_v2.argtypes]
3 = "RefOrCuRef{Cdouble}"
4 = "CuPtr{cuDoubleComplex}"

[api.cublasAxpyEx.argtypes]
3 = "PtrOrCuPtr{Cvoid}"
5 = "CuPtr{Cvoid}"
8 = "CuPtr{Cvoid}"

[api."cublasğ•axpy_v2".argtypes]
3 = "RefOrCuRef{T}"
4 = "CuPtr{T}"
6 = "CuPtr{T}"

[api.cublasCopyEx.argtypes]
3 = "CuPtr{Cvoid}"
6 = "CuPtr{Cvoid}"

[api."cublasğ•copy_v2".argtypes]
3 = "CuPtr{T}"
5 = "CuPtr{T}"

[api."cublasğ•swap_v2".argtypes]
3 = "CuPtr{T}"
5 = "CuPtr{T}"

[api.cublasSwapEx.argtypes]
3 = "CuPtr{Cvoid}"
6 = "CuPtr{Cvoid}"

[api.cublasIsamax_v2.argtypes]
3 = "CuPtr{Cfloat}"
5 = "RefOrCuRef{Cint}"

[api.cublasIdamax_v2.argtypes]
3 = "CuPtr{Cdouble}"
5 = "RefOrCuRef{Cint}"

[api.cublasIcamax_v2.argtypes]
3 = "CuPtr{cuComplex}"
5 = "RefOrCuRef{Cint}"

[api.cublasIzamax_v2.argtypes]
3 = "CuPtr{cuDoubleComplex}"
5 = "RefOrCuRef{Cint}"

[api.cublasIamaxEx.argtypes]
3 = "CuPtr{Cvoid}"
6 = "RefOrCuRef{Cint}"

[api.cublasIsamin_v2.argtypes]
3 = "CuPtr{Cfloat}"
5 = "RefOrCuRef{Cint}"

[api.cublasIdamin_v2.argtypes]
3 = "CuPtr{Cdouble}"
5 = "RefOrCuRef{Cint}"

[api.cublasIcamin_v2.argtypes]
3 = "CuPtr{cuComplex}"
5 = "RefOrCuRef{Cint}"

[api.cublasIzamin_v2.argtypes]
3 = "CuPtr{cuDoubleComplex}"
5 = "RefOrCuRef{Cint}"

[api.cublasIaminEx.argtypes]
3 = "CuPtr{Cvoid}"
6 = "RefOrCuRef{Cint}"

[api.cublasAsumEx.argtypes]
3 = "CuPtr{Cvoid}"
6 = "PtrOrCuPtr{Cvoid}"

[api."cublasğ•asum_v2".argtypes]
3 = "CuPtr{T}"
5 = "RefOrCuRef{T}"

[api.cublasScasum_v2.argtypes]
3 = "CuPtr{cuComplex}"
5 = "RefOrCuRef{Cfloat}"

[api.cublasDzasum_v2.argtypes]
3 = "CuPtr{cuDoubleComplex}"
5 = "RefOrCuRef{Cdouble}"

[api."cublasğ•rot_v2".argtypes]
3 = "CuPtr{T}"
5 = "CuPtr{T}"
7 = "RefOrCuRef{S}"
8 = "RefOrCuRef{T}"

[api.cublasCsrot_v2.argtypes]
3 = "CuPtr{cuComplex}"
5 = "CuPtr{cuComplex}"
7 = "RefOrCuRef{Cfloat}"
8 = "RefOrCuRef{Cfloat}"

[api.cublasZdrot_v2.argtypes]
3 = "CuPtr{cuDoubleComplex}"
5 = "CuPtr{cuDoubleComplex}"
7 = "RefOrCuRef{Cdouble}"
8 = "RefOrCuRef{Cdouble}"

[api.cublasRotEx.argtypes]
3 = "CuPtr{Cvoid}"
6 = "CuPtr{Cvoid}"
9 = "PtrOrCuPtr{Cvoid}"
10 = "PtrOrCuPtr{Cvoid}"

[api."cublasğ•rotg_v2".argtypes]
2 = "RefOrCuRef{T}"
3 = "RefOrCuRef{T}"
4 = "PtrOrCuPtr{S}"
5 = "PtrOrCuPtr{T}"

[api.cublasRotgEx.argtypes]
5 = "PtrOrCuPtr{Cvoid}"
6 = "PtrOrCuPtr{Cvoid}"

[api."cublasğ•rotm_v2".argtypes]
3 = "CuPtr{T}"
5 = "CuPtr{T}"
7 = "PtrOrCuPtr{T}"

[api.cublasRotmEx.argtypes]
3 = "CuPtr{Cvoid}"
6 = "CuPtr{Cvoid}"
9 = "PtrOrCuPtr{Cvoid}"

[api."cublasğ•rotmg_v2".argtypes]
2 = "RefOrCuRef{T}"
3 = "RefOrCuRef{T}"
4 = "RefOrCuRef{T}"
5 = "RefOrCuRef{T}"
6 = "PtrOrCuPtr{T}"

[api.cublasRotmgEx.argtypes]
2 = "PtrOrCuPtr{Cvoid}"
4 = "PtrOrCuPtr{Cvoid}"
6 = "PtrOrCuPtr{Cvoid}"
8 = "PtrOrCuPtr{Cvoid}"
10 = "PtrOrCuPtr{Cvoid}"

[api."cublasğ•gemv_v2".argtypes]
5 = "RefOrCuRef{T}"
6 = "CuPtr{T}"
8 = "CuPtr{T}"
10 = "RefOrCuRef{T}"
11 = "CuPtr{T}"

[api."cublasğ•gbmv_v2".argtypes]
7 = "RefOrCuRef{T}"
8 = "CuPtr{T}"
10 = "CuPtr{T}"
12 = "RefOrCuRef{T}"
13 = "CuPtr{T}"

[api."cublasğ•trmv_v2".argtypes]
6 = "CuPtr{T}"
8 = "CuPtr{T}"

[api."cublasğ•tbmv_v2".argtypes]
7 = "CuPtr{T}"
9 = "CuPtr{T}"

[api."cublasğ•tpmv_v2".argtypes]
6 = "CuPtr{T}"
7 = "CuPtr{T}"

[api."cublasğ•gemvBatched".argtypes]
5 = "RefOrCuRef{T}"
6 = "CuPtr{Ptr{T}}"
8 = "CuPtr{Ptr{T}}"
10 = "RefOrCuRef{T}"
11 = "CuPtr{Ptr{T}}"

[api.cublasHSHgemvBatched.argtypes]
5 = "RefOrCuRef{Cfloat}"
6 = "CuPtr{Ptr{Float16}}"
8 = "CuPtr{Ptr{Float16}}"
10 = "RefOrCuRef{Cfloat}"
11 = "CuPtr{Ptr{Float16}}"

[api.cublasHSSgemvBatched.argtypes]
5 = "RefOrCuRef{Cfloat}"
6 = "CuPtr{Ptr{Float16}}"
8 = "CuPtr{Ptr{Float16}}"
10 = "RefOrCuRef{Cfloat}"
11 = "CuPtr{Ptr{Cfloat}}"

[api."cublasğ•gemvStridedBatched".argtypes]
5 = "RefOrCuRef{T}"
6 = "CuPtr{T}"
9 = "CuPtr{T}"
12 = "RefOrCuRef{T}"
13 = "CuPtr{T}"

[api.cublasHSSgemvStridedBatched.argtypes]
5 = "RefOrCuRef{Cfloat}"
6 = "CuPtr{Float16}"
9 = "CuPtr{Float16}"
12 = "RefOrCuRef{Cfloat}"
13 = "CuPtr{Cfloat}"

[api.cublasTSTgemvStridedBatched.argtypes]
5 = "RefOrCuRef{Cfloat}"
6 = "CuPtr{BFloat16}"
9 = "CuPtr{BFloat16}"
12 = "RefOrCuRef{Cfloat}"
13 = "CuPtr{BFloat16}"

[api.cublasTSSgemvStridedBatched.argtypes]
5 = "RefOrCuRef{Cfloat}"
6 = "CuPtr{BFloat16}"
9 = "CuPtr{BFloat16}"
12 = "RefOrCuRef{Cfloat}"
13 = "CuPtr{Cfloat}"

[api."cublasğ•trsv_v2".argtypes]
6 = "CuPtr{T}"
8 = "CuPtr{T}"

[api."cublasğ•tpsv_v2".argtypes]
6 = "CuPtr{T}"
7 = "CuPtr{T}"

[api."cublasğ•tbsv_v2".argtypes]
7 = "CuPtr{T}"
9 = "CuPtr{T}"

[api."cublasğ•symv_v2".argtypes]
4 = "RefOrCuRef{T}"
5 = "CuPtr{T}"
7 = "CuPtr{T}"
9 = "RefOrCuRef{T}"
10 = "CuPtr{T}"

[api."cublasğ•hemv_v2".argtypes]
4 = "RefOrCuRef{T}"
5 = "CuPtr{T}"
7 = "CuPtr{T}"
9 = "RefOrCuRef{T}"
10 = "CuPtr{T}"

[api."cublasğ•sbmv_v2".argtypes]
5 = "RefOrCuRef{T}"
6 = "CuPtr{T}"
8 = "CuPtr{T}"
10 = "RefOrCuRef{T}"
11 = "CuPtr{T}"

[api."cublasğ•hbmv_v2".argtypes]
5 = "RefOrCuRef{T}"
6 = "CuPtr{T}"
8 = "CuPtr{T}"
10 = "RefOrCuRef{T}"
11 = "CuPtr{T}"

[api."cublasğ•spmv_v2".argtypes]
4 = "RefOrCuRef{T}"
5 = "CuPtr{T}"
6 = "CuPtr{T}"
8 = "RefOrCuRef{T}"
9 = "CuPtr{T}"

[api."cublasğ•hpmv_v2".argtypes]
4 = "RefOrCuRef{T}"
5 = "CuPtr{T}"
6 = "CuPtr{T}"
8 = "RefOrCuRef{T}"
9 = "CuPtr{T}"

[api."cublasğ•ger_v2".argtypes]
4 = "RefOrCuRef{T}"
5 = "CuPtr{T}"
7 = "CuPtr{T}"
9 = "CuPtr{T}"

[api."cublasğ•geru_v2".argtypes]
4 = "RefOrCuRef{T}"
5 = "CuPtr{T}"
7 = "CuPtr{T}"
9 = "CuPtr{T}"

[api."cublasğ•gerc_v2".argtypes]
4 = "RefOrCuRef{T}"
5 = "CuPtr{T}"
7 = "CuPtr{T}"
9 = "CuPtr{T}"

[api."cublasğ•syr_v2".argtypes]
4 = "RefOrCuRef{T}"
5 = "CuPtr{T}"
7 = "CuPtr{T}"

[api."cublasğ•her_v2".argtypes]
4 = "RefOrCuRef{S}"
5 = "CuPtr{T}"
7 = "CuPtr{T}"

[api."cublasğ•spr_v2".argtypes]
4 = "RefOrCuRef{T}"
5 = "CuPtr{T}"
7 = "CuPtr{T}"

[api."cublasğ•hpr_v2".argtypes]
4 = "RefOrCuRef{S}"
5 = "CuPtr{T}"
7 = "CuPtr{T}"

[api."cublasğ•syr2_v2".argtypes]
4 = "RefOrCuRef{T}"
5 = "CuPtr{T}"
7 = "CuPtr{T}"
9 = "CuPtr{T}"

[api."cublasğ•her2_v2".argtypes]
4 = "RefOrCuRef{T}"
5 = "CuPtr{T}"
7 = "CuPtr{T}"
9 = "CuPtr{T}"

[api."cublasğ•spr2_v2".argtypes]
4 = "RefOrCuRef{T}"
5 = "CuPtr{T}"
7 = "CuPtr{T}"
9 = "CuPtr{T}"

[api."cublasğ•hpr2_v2".argtypes]
4 = "RefOrCuRef{T}"
5 = "CuPtr{T}"
7 = "CuPtr{T}"
9 = "CuPtr{T}"

[api."cublasğ•gemm_v2".argtypes]
7 = "RefOrCuRef{T}"
8 = "CuPtr{T}"
10 = "CuPtr{T}"
12 = "RefOrCuRef{T}"
13 = "CuPtr{T}"

[api."cublasğ•gemm3m".argtypes]
7 = "RefOrCuRef{T}"
8 = "CuPtr{T}"
10 = "CuPtr{T}"
12 = "RefOrCuRef{T}"
13 = "CuPtr{T}"

[api."cublasğ•gemm3mEx".argtypes]
7 = "RefOrCuRef{T}"
8 = "CuPtr{Cvoid}"
11 = "CuPtr{Cvoid}"
14 = "RefOrCuRef{T}"
15 = "CuPtr{Cvoid}"

[api."cublasğ•gemmEx".argtypes]
7 = "RefOrCuRef{T}"
8 = "CuPtr{Cvoid}"
11 = "CuPtr{Cvoid}"
14 = "RefOrCuRef{T}"
15 = "CuPtr{Cvoid}"

[api.cublasGemmEx.argtypes]
7 = "PtrOrCuPtr{Cvoid}"
8 = "CuPtr{Cvoid}"
11 = "CuPtr{Cvoid}"
14 = "PtrOrCuPtr{Cvoid}"
15 = "CuPtr{Cvoid}"

[api.cublasUint8gemmBias.argtypes]
8 = "CuPtr{Cuchar}"
11 = "CuPtr{Cuchar}"
14 = "CuPtr{Cuchar}"

[api."cublasğ•syrk_v2".argtypes]
6 = "RefOrCuRef{T}"
7 = "CuPtr{T}"
9 = "RefOrCuRef{T}"
10 = "CuPtr{T}"

[api."cublasğ•syrkEx".argtypes]
6 = "RefOrCuRef{T}"
7 = "CuPtr{Cvoid}"
10 = "RefOrCuRef{T}"
11 = "CuPtr{Cvoid}"

[api."cublasğ•syrk3mEx".argtypes]
6 = "RefOrCuRef{T}"
7 = "CuPtr{Cvoid}"
10 = "RefOrCuRef{T}"
11 = "CuPtr{Cvoid}"

[api."cublasğ•herk_v2".argtypes]
6 = "RefOrCuRef{S}"
7 = "CuPtr{T}"
9 = "RefOrCuRef{S}"
10 = "CuPtr{T}"

[api."cublasğ•herkEx".argtypes]
6 = "RefOrCuRef{S}"
7 = "CuPtr{Cvoid}"
10 = "RefOrCuRef{S}"
11 = "CuPtr{Cvoid}"

[api."cublasğ•herk3mEx".argtypes]
6 = "RefOrCuRef{S}"
7 = "CuPtr{Cvoid}"
10 = "RefOrCuRef{S}"
11 = "CuPtr{Cvoid}"

[api."cublasğ•syr2k_v2".argtypes]
6 = "RefOrCuRef{T}"
7 = "CuPtr{T}"
9 = "CuPtr{T}"
11 = "RefOrCuRef{T}"
12 = "CuPtr{T}"

[api."cublasğ•her2k_v2".argtypes]
6 = "RefOrCuRef{T}"
7 = "CuPtr{T}"
9 = "CuPtr{T}"
11 = "RefOrCuRef{S}"
12 = "CuPtr{T}"

[api."cublasğ•syrkx".argtypes]
6 = "RefOrCuRef{T}"
7 = "CuPtr{T}"
9 = "CuPtr{T}"
11 = "RefOrCuRef{T}"
12 = "CuPtr{T}"

[api."cublasğ•herkx".argtypes]
6 = "RefOrCuRef{T}"
7 = "CuPtr{T}"
9 = "CuPtr{T}"
11 = "RefOrCuRef{S}"
12 = "CuPtr{T}"

[api."cublasğ•symm_v2".argtypes]
6 = "RefOrCuRef{T}"
7 = "CuPtr{T}"
9 = "CuPtr{T}"
11 = "RefOrCuRef{T}"
12 = "CuPtr{T}"

[api."cublasğ•hemm_v2".argtypes]
6 = "RefOrCuRef{T}"
7 = "CuPtr{T}"
9 = "CuPtr{T}"
11 = "RefOrCuRef{T}"
12 = "CuPtr{T}"

[api."cublasğ•trsm_v2".argtypes]
8 = "RefOrCuRef{T}"
9 = "CuPtr{T}"
11 = "CuPtr{T}"

[api."cublasğ•trmm_v2".argtypes]
8 = "RefOrCuRef{T}"
9 = "CuPtr{T}"
11 = "CuPtr{T}"
13 = "CuPtr{T}"

[api."cublasğ•gemmBatched".argtypes]
7 = "RefOrCuRef{T}"
8 = "CuPtr{Ptr{T}}"
10 = "CuPtr{Ptr{T}}"
12 = "RefOrCuRef{T}"
13 = "CuPtr{Ptr{T}}"

[api."cublasğ•gemm3mBatched".argtypes]
7 = "RefOrCuRef{T}"
8 = "CuPtr{Ptr{T}}"
10 = "CuPtr{Ptr{T}}"
12 = "RefOrCuRef{T}"
13 = "CuPtr{Ptr{T}}"

[api.cublasGemmBatchedEx.argtypes]
7 = "PtrOrCuPtr{Cvoid}"
8 = "CuPtr{Ptr{Cvoid}}"
11 = "CuPtr{Ptr{Cvoid}}"
14 = "PtrOrCuPtr{Cvoid}"
15 = "CuPtr{Ptr{Cvoid}}"

[api.cublasGemmStridedBatchedEx.argtypes]
7 = "PtrOrCuPtr{Cvoid}"
8 = "CuPtr{Cvoid}"
12 = "CuPtr{Cvoid}"
16 = "PtrOrCuPtr{Cvoid}"
17 = "CuPtr{Cvoid}"

[api."cublasğ•gemmStridedBatched".argtypes]
7 = "RefOrCuRef{T}"
8 = "CuPtr{T}"
11 = "CuPtr{T}"
14 = "RefOrCuRef{T}"
15 = "CuPtr{T}"

[api."cublasğ•gemm3mStridedBatched".argtypes]
7 = "RefOrCuRef{T}"
8 = "CuPtr{T}"
11 = "CuPtr{T}"
14 = "RefOrCuRef{T}"
15 = "CuPtr{T}"

[api."cublasğ•geam".argtypes]
6 = "RefOrCuRef{T}"
7 = "CuPtr{T}"
9 = "RefOrCuRef{T}"
10 = "CuPtr{T}"
12 = "CuPtr{T}"

[api."cublasğ•getrfBatched".argtypes]
3 = "CuPtr{Ptr{T}}"
5 = "CuPtr{Cint}"
6 = "CuPtr{Cint}"

[api."cublasğ•getriBatched".argtypes]
3 = "CuPtr{Ptr{T}}"
5 = "CuPtr{Cint}"
6 = "CuPtr{Ptr{T}}"
8 = "CuPtr{Cint}"

[api."cublasğ•getrsBatched".argtypes]
5 = "CuPtr{Ptr{T}}"
7 = "CuPtr{Cint}"
8 = "CuPtr{Ptr{T}}"

[api."cublasğ•trsmBatched".argtypes]
8 = "RefOrCuRef{T}"
9 = "CuPtr{Ptr{T}}"
11 = "CuPtr{Ptr{T}}"

[api."cublasğ•matinvBatched".argtypes]
3 = "CuPtr{Ptr{T}}"
5 = "CuPtr{Ptr{T}}"
7 = "CuPtr{Cint}"

[api."cublasğ•geqrfBatched".argtypes]
4 = "CuPtr{Ptr{T}}"
6 = "CuPtr{Ptr{T}}"

[api."cublasğ•gelsBatched".argtypes]
6 = "CuPtr{Ptr{T}}"
8 = "CuPtr{Ptr{T}}"
11 = "CuPtr{Cint}"

[api."cublasğ•dgmm".argtypes]
5 = "CuPtr{T}"
7 = "CuPtr{T}"
9 = "CuPtr{T}"

[api."cublasğ•tpttr".argtypes]
4 = "CuPtr{T}"
5 = "CuPtr{T}"

[api."cublasğ•trttp".argtypes]
4 = "CuPtr{T}"
6 = "CuPtr{T}"

[api."cublasXtğ•gemm".argtypes]
7 = "RefOrCuRef{T}"
8 = "PtrOrCuPtr{T}"
10 = "PtrOrCuPtr{T}"
12 = "RefOrCuRef{T}"
13 = "PtrOrCuPtr{T}"

[api."cublasXtğ•syrk".argtypes]
6 = "RefOrCuRef{T}"
7 = "PtrOrCuPtr{T}"
9 = "RefOrCuRef{T}"
10 = "PtrOrCuPtr{T}"

[api."cublasXtğ•herk".argtypes]
6 = "RefOrCuRef{S}"
7 = "PtrOrCuPtr{T}"
9 = "RefOrCuRef{S}"
10 = "PtrOrCuPtr{T}"

[api."cublasXtğ•syr2k".argtypes]
6 = "RefOrCuRef{T}"
7 = "PtrOrCuPtr{T}"
9 = "PtrOrCuPtr{T}"
11 = "RefOrCuRef{T}"
12 = "PtrOrCuPtr{T}"

[api."cublasXtğ•herkx".argtypes]
6 = "RefOrCuRef{T}"
7 = "PtrOrCuPtr{T}"
9 = "PtrOrCuPtr{T}"
11 = "RefOrCuRef{S}"
12 = "PtrOrCuPtr{T}"

[api."cublasXtğ•trsm".argtypes]
8 = "RefOrCuRef{T}"
9 = "PtrOrCuPtr{T}"
11 = "PtrOrCuPtr{T}"

[api."cublasXtğ•symm".argtypes]
6 = "RefOrCuRef{T}"
7 = "PtrOrCuPtr{T}"
9 = "PtrOrCuPtr{T}"
11 = "RefOrCuRef{T}"
12 = "PtrOrCuPtr{T}"

[api."cublasXtğ•hemm".argtypes]
6 = "RefOrCuRef{T}"
7 = "PtrOrCuPtr{T}"
9 = "PtrOrCuPtr{T}"
11 = "RefOrCuRef{T}"
12 = "PtrOrCuPtr{T}"

[api."cublasXtğ•syrkx".argtypes]
6 = "RefOrCuRef{T}"
7 = "PtrOrCuPtr{T}"
9 = "PtrOrCuPtr{T}"
11 = "RefOrCuRef{T}"
12 = "PtrOrCuPtr{T}"

[api."cublasXtğ•her2k".argtypes]
6 = "RefOrCuRef{T}"
7 = "PtrOrCuPtr{T}"
9 = "PtrOrCuPtr{T}"
11 = "RefOrCuRef{S}"
12 = "PtrOrCuPtr{T}"

[api."cublasXtğ•spmm".argtypes]
6 = "Ref{T}"
8 = "PtrOrCuPtr{T}"
10 = "Ref{T}"
11 = "PtrOrCuPtr{T}"

[api."cublasXtğ•trmm".argtypes]
8 = "RefOrCuRef{T}"
9 = "PtrOrCuPtr{T}"
11 = "PtrOrCuPtr{T}"
13 = "PtrOrCuPtr{T}"

[api.cublasSetWorkspace_v2.argtypes]
2 = "CuPtr{Cvoid}"

[api."cublasğ•gemmGroupedBatched".argtypes]
8 = "CuPtr{Ptr{T}}"
10 = "CuPtr{Ptr{T}}"
13 = "CuPtr{Ptr{T}}"
