# This file is machine-generated - editing it directly is not advised

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[CEnum]]
git-tree-sha1 = "215a9aa4a1f23fbd05b92769fdd62559488d70e9"
uuid = "fa961155-64e5-5f13-b03f-caf6b980ea82"
version = "0.4.1"

[[CSTParser]]
deps = ["Tokenize"]
git-tree-sha1 = "f91b4c10ddaad564e20daa0ec55994dc1302239e"
uuid = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
version = "2.4.0"

[[CUDA_full_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "e8f3e40eeb7c9f17cb39257b048a3a36cc2d377e"
uuid = "4f82f1eb-248c-5f56-a42e-99106d144614"
version = "11.0.2+0"

[[CUDA_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "e61af4d4e129e6a900dbd70e704cb02518d76593"
uuid = "e9e359dc-d701-5aa8-82ae-09bbf812ea83"
version = "10.2.89+1"

[[CUDNN_CUDA102_jll]]
deps = ["CUDA_jll", "Libdl", "Pkg"]
git-tree-sha1 = "cb7cab833eeeb72956a070bfc974d18c914c021c"
uuid = "8ba91e8f-b0e5-5ca0-b631-aadbb9431ebf"
version = "7.6.5+0"

[[CUTENSOR_CUDA102_jll]]
deps = ["CUDA_jll", "Libdl", "Pkg"]
git-tree-sha1 = "78ae0518b8e6da32862537dcc84b7a36a42ca2a7"
uuid = "3383e110-d2c8-5588-847f-51a846eee08b"
version = "1.1.0+0"

[[Clang]]
deps = ["CEnum", "DataStructures", "LLVM_jll", "Libdl"]
git-tree-sha1 = "21198ff2d90da6583bf9ea93c3807a762171a41a"
uuid = "40e3b903-d033-50b4-a0cc-940c62c95e31"
version = "0.11.1"

[[Crayons]]
git-tree-sha1 = "c437a9c2114c7ba19322712e58942b383ffbd6c0"
uuid = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
version = "4.0.3"

[[DataStructures]]
deps = ["InteractiveUtils", "OrderedCollections"]
git-tree-sha1 = "edad9434967fdc0a2631a65d902228400642120c"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.17.19"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[LLVM_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "c037c15f36c185c613e5b2589d5833720dab3f76"
uuid = "86de99a1-58d6-5da7-8064-bd56ce2e322c"
version = "8.0.1+0"

[[LibGit2]]
deps = ["Printf"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[OrderedCollections]]
git-tree-sha1 = "293b70ac1780f9584c89268a6e2a560d938a7065"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.3.0"

[[Pkg]]
deps = ["Dates", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[Tokenize]]
git-tree-sha1 = "73c00ad506d88a7e8e4f90f48a70943101728227"
uuid = "0796e94c-ce3b-5d07-9a54-7f471281c624"
version = "0.5.8"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
