# This file is machine-generated - editing it directly is not advised

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[CEnum]]
git-tree-sha1 = "215a9aa4a1f23fbd05b92769fdd62559488d70e9"
uuid = "fa961155-64e5-5f13-b03f-caf6b980ea82"
version = "0.4.1"

[[CSTParser]]
deps = ["Tokenize"]
git-tree-sha1 = "60e9121d9ea044c30a04397e59b00c5d9eb826ee"
uuid = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
version = "2.5.0"

[[CUDA_full_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "a6da074d8eeb39a6d9160a662a56c3b52e0f26bc"
uuid = "4f82f1eb-248c-5f56-a42e-99106d144614"
version = "11.0.3+0"

[[CUDA_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "8ff156ee37c13aaf8f77ca7d2ecf47d8895d3974"
uuid = "e9e359dc-d701-5aa8-82ae-09bbf812ea83"
version = "11.0.2+1"

[[CUDNN_CUDA110_jll]]
deps = ["CUDA_jll", "Libdl", "Pkg"]
git-tree-sha1 = "e3748df890eae7c39040cd50a4adcb4b054e6f12"
uuid = "5fa5d4a9-0408-52e0-9638-7667eddd2fce"
version = "8.0.2+0"

[[CUTENSOR_CUDA110_jll]]
deps = ["CUDA_jll", "CompilerSupportLibraries_jll", "Libdl", "Pkg"]
git-tree-sha1 = "a3637919efe99f42cb226d75a3e2f62a2012e4b6"
uuid = "004fe424-f3b5-51a0-a814-026e7c39908e"
version = "1.2.0+0"

[[Clang]]
deps = ["CEnum", "Clang_jll", "DataStructures", "Libdl"]
git-tree-sha1 = "1530e0c7012988bdd1a0720ce130ae28a6d22dff"
uuid = "40e3b903-d033-50b4-a0cc-940c62c95e31"
version = "0.12.0"

[[Clang_jll]]
deps = ["Libdl", "Pkg", "libLLVM_jll"]
git-tree-sha1 = "ff31103423b99f59859d4b0505af4093a1e99079"
uuid = "0ee61d77-7f21-5576-8119-9fcc46b10100"
version = "9.0.1+4"

[[CompilerSupportLibraries_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "7c4f882c41faa72118841185afc58a2eb00ef612"
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version = "0.3.3+0"

[[Crayons]]
git-tree-sha1 = "3f71217b538d7aaee0b69ab47d9b7724ca8afa0d"
uuid = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
version = "4.0.4"

[[DataStructures]]
deps = ["InteractiveUtils", "OrderedCollections"]
git-tree-sha1 = "88d48e133e6d3dd68183309877eac74393daa7eb"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.17.20"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[LibGit2]]
deps = ["Printf"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[OrderedCollections]]
git-tree-sha1 = "293b70ac1780f9584c89268a6e2a560d938a7065"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.3.0"

[[Pkg]]
deps = ["Dates", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[Tokenize]]
git-tree-sha1 = "73c00ad506d88a7e8e4f90f48a70943101728227"
uuid = "0796e94c-ce3b-5d07-9a54-7f471281c624"
version = "0.5.8"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[libLLVM_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "8bbcb2ac071438cd061ac210f6ba6754f45b8672"
uuid = "8f36deef-c2a5-5394-99ed-8e07531fb29a"
version = "9.0.1+5"
