[deps]
CSTParser = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
CUDAapi = "3895d2a7-ec45-59b8-82bb-cfc6a382f9b3"
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
Tokenize = "0796e94c-ce3b-5d07-9a54-7f471281c624"
